# Generated by Django 3.2 on 2021-04-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputText', models.CharField(max_length=10000000)),
                ('summarizedText', models.CharField(max_length=10000000)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
