# Generated by Django 3.2.3 on 2021-05-18 13:37

from django.db import migrations, models
import django_lifecycle.mixins
import textSum.models
import textSum.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputText', models.CharField(blank=True, max_length=10000000)),
                ('summarizedText', models.CharField(blank=True, max_length=10000000)),
                ('upload', models.FileField(blank=True, upload_to=textSum.models.PathAndRename('uploads/'), validators=[textSum.validators.validate_file_extension])),
                ('completed', models.BooleanField(default=False)),
                ('transactionID', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('summaryType', models.CharField(blank=True, max_length=10000000)),
                ('scores', models.JSONField(default=list)),
            ],
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
