# Generated by Django 3.2 on 2021-04-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textSum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='summarizedText',
            field=models.CharField(blank=True, max_length=10000000),
        ),
    ]
