# Generated by Django 3.2 on 2021-04-09 16:14

from django.db import migrations, models
import textSum.validators


class Migration(migrations.Migration):

    dependencies = [
        ('textSum', '0002_alter_text_summarizedtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/', validators=[textSum.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='text',
            name='inputText',
            field=models.CharField(blank=True, max_length=10000000),
        ),
    ]
