# Generated by Django 3.2 on 2021-04-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textSum', '0003_auto_20210409_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='file',
            new_name='upload',
        ),
    ]
