# Generated by Django 3.2 on 2021-04-10 15:05

from django.db import migrations, models
import textSum.models
import textSum.validators


class Migration(migrations.Migration):

    dependencies = [
        ('textSum', '0004_rename_file_text_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='upload',
            field=models.FileField(blank=True, upload_to=textSum.models.PathAndRename('/uploads'), validators=[textSum.validators.validate_file_extension]),
        ),
    ]
