# Generated by Django 3.2.3 on 2021-05-18 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('textSum', '0006_auto_20210410_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='scores',
            field=models.JSONField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='summaryType',
            field=models.CharField(blank=True, max_length=10000000),
        ),
    ]
