# Generated by Django 3.2.3 on 2021-05-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textSum', '0007_auto_20210518_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='scores',
            field=models.JSONField(default=[]),
        ),
    ]
