# Generated by Django 3.2.3 on 2021-05-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textSum', '0008_alter_text_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='scores',
            field=models.JSONField(default=list),
        ),
    ]
